info:
  title: "My API"
  version: "1.0.0"

openapi: 3.0.0
paths:
  /:
    get:
      summary: "Say hello"
      operationId: functions.functions.say_hello
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        304:
          description: "Not Modified"


  /get_users:
    get:
      summary: "Get users"
      description: |
        This is a description of the endpoint.
      operationId: functions.functions.get_users
      responses:
        200:
          $ref: "#/components/responses/users"
        304:
          description: "Not Modified"

  /get_user_by_id:
    get:
      summary: "Get user by ID"
      operationId: functions.functions.get_user_by_id
      parameters:
        - name: id
          in: query
          description: "User ID"
          required: true
          schema:
            type: integer
      responses:
        200:
          $ref: "#/components/responses/users"
        304:
          description: "Not Modified"

  /create_user:
    post:
      summary: "Create user"
      operationId: functions.functions.create_user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        200:
          $ref: "#/components/responses/users"
        304:
          description: "Not Modified"

components:
  responses:
    users:
      description: "OK"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/user"
            example: |
              [
                {
                  "id": 1,
                  "name": "John",
                  "age": 30
                },
                {
                  "id": 2,
                  "name": "Jane",
                  "age": 25
                }
              ]
  schemas:
    user:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer

